//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskApproval
    {
        public int TaskApprovalId { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public string PlayerNumber { get; set; }
        public string Owner { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsClosed { get; set; }
    }
}
